# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a69951e1677fb26511ca907b886255861a0e59f736e4c0bccf1714a4f52d8979b03672ff680dace87a063a1c64d0b42d815e1cb78d7ed2d52cebf6e93b1261b

test:
  secret_key_base: ef86d09c391cde8dc6b3583ea2705f260c0a727defb4460fe3dfdf3ab4f0f17aa859cc73805a58b5da05ae19e4145dd711452805c4550bea08b5b6cec7178266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
